# Generated by Django 5.0.1 on 2024-02-18 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0007_alter_course_syllabus'),
        ('dashboard', '0002_gradenotification_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradenotification',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coursework.course'),
        ),
    ]
