# Generated by Django 5.0.1 on 2024-02-19 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0014_submission_graded_at'),
        ('dashboard', '0003_gradenotification_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradenotification',
            old_name='message',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='gradenotification',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment'),
        ),
    ]
