# Generated by Django 5.0.1 on 2024-02-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('student', 'Student'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
