# Generated by Django 5.0.1 on 2024-02-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0005_alter_usercourse_options_usercourse_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourseOrder',
        ),
    ]
