# Generated by Django 5.0.1 on 2024-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0006_delete_usercourseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/%d/'),
        ),
    ]
