# Generated by Django 5.0.2 on 2024-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
