# Generated by Django 5.0.1 on 2024-02-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_message_options_rename_message_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
