# Generated by Django 5.0.1 on 2024-02-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_submission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
