# Generated by Django 5.0.1 on 2024-02-07 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='file',
        ),
    ]
