# Generated by Django 5.0.1 on 2024-02-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_remove_feedback_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='file',
            field=models.FileField(null=True, upload_to='feedback/%Y/%m/%d/'),
        ),
    ]
