# Generated by Django 5.0.1 on 2024-02-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_feedback_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='feedback/%Y/%m/%d/'),
        ),
    ]
