# Generated by Django 5.0.1 on 2024-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_alter_feedback_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='graded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
