# Generated by Django 5.0.1 on 2024-02-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0004_course_syllabus'),
        ('onlinelearning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontent',
            name='assignment',
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_contents', to='coursework.course'),
        ),
    ]
