# Generated by Django 5.0.1 on 2024-02-07 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0004_course_syllabus'),
        ('onlinelearning', '0002_remove_usercontent_assignment_module_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='coursework.course'),
        ),
    ]
