# Generated by Django 5.0.1 on 2024-02-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0003_alter_module_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
