# Generated by Django 5.0.1 on 2024-02-07 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_alter_feedback_file'),
        ('onlinelearning', '0008_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('file', 'File'), ('url', 'URL'), ('text', 'Text'), ('assignment', 'Assignment')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('url', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
