# Generated by Django 5.0.1 on 2024-02-07 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0009_customcontent_delete_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcontent',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinelearning.module'),
        ),
        migrations.AlterField(
            model_name='customcontent',
            name='content_type',
            field=models.CharField(choices=[('file', 'File'), ('url', 'URL'), ('text', 'Text'), ('assignment', 'Assignment'), ('module', 'Module')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customcontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
