# Generated by Django 5.0.1 on 2024-02-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0010_customcontent_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcontent',
            name='urltext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customcontent',
            name='content_type',
            field=models.CharField(choices=[('file', 'File'), ('url', 'URL'), ('text', 'Text'), ('assignment', 'Assignment'), ('module', 'Module'), ('urltext', 'URLText')], max_length=10),
        ),
    ]
