# Generated by Django 4.2.6 on 2024-02-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0011_customcontent_urltext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcontent',
            name='urltext',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
