# Generated by Django 5.0.1 on 2024-02-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0012_alter_customcontent_urltext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcontent',
            name='content_type',
            field=models.CharField(choices=[('file', 'File'), ('url', 'URL'), ('text', 'Text'), ('assignment', 'Assignment'), ('urltext', 'URLText')], max_length=10),
        ),
    ]
