# Generated by Django 5.0.1 on 2024-02-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0013_alter_customcontent_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcontent',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
