# Generated by Django 4.2.7 on 2024-02-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0014_customcontent_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcontent',
            name='posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
